// Copies examples/demo-projects/*.json (the canonical source, generated by
// packages/harmony-core/scripts/generate-examples.ts) into public/samples/
// so the web app can fetch them at runtime without bundling them into the
// JS payload. Runs automatically before `dev`/`build` (see package.json) —
// public/samples/ is gitignored so there's exactly one source of truth.
import { existsSync, mkdirSync, readdirSync, copyFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SOURCE_DIR = join(__dirname, "..", "..", "..", "examples", "demo-projects");
const TARGET_DIR = join(__dirname, "..", "public", "samples");

if (!existsSync(SOURCE_DIR)) {
  console.warn(`[sync-samples] ${SOURCE_DIR} not found — skipping (no samples will be available).`);
  process.exit(0);
}

mkdirSync(TARGET_DIR, { recursive: true });

const files = readdirSync(SOURCE_DIR).filter((f) => f.endsWith(".json"));
for (const file of files) {
  copyFileSync(join(SOURCE_DIR, file), join(TARGET_DIR, file));
}
console.log(`[sync-samples] copied ${files.length} sample project(s) to public/samples/`);
